### ISSUE TITLE
Saldo de Fornecedores

### ISSUE THREAD

**Issue by mchaubert** [totvs/ttalk-standard-message#698]
#### Agrupador de negócio

- [ ] Agroindústria

- [ ] Serviços

- [ ] Construção e Projetos

- [ ] Saúde

- [ ] Recursos Humanos

- [ ] Educacional

- [ ] Manufatura

- [ ] Distribuição e Logística

- [ ] Foundation

- [ ] Varejo

- [ ] E-Commerce

- [ ] Supply Chain

- [ ] Geral

- [ ] TMS

- [ ] BackOffice

- [ ] Compras

- [ ] Quality

- [ ] healthcare

**Comment by dreissonmr** [comment]
Boa Tarde,

Por favor preencher o template, para que possamos obter mais informações sobre a sua sugestão.

As informações iniciais são: **Nome da API, Descrição da API, Produto e Agrupador de negócio.**

Obrigado

**Comment by dreissonmr** [comment]
Devido a falta de informações e o não preenchimento do template, a issue será finalizada.
