### ISSUE TITLE
Solicitação ao Armazém

### ISSUE THREAD

**Issue by flaviodiasservitec** [totvs/ttalk-standard-message#784]
#### Material

- [ ] Agroindústria

- [ ] Serviços

- [ ] Construção e Projetos

- [ ] Saúde

- [ ] Recursos Humanos

- [ ] Educacional

- [ ] Manufatura

- [ ] Distribuição e Logística

- [ ] Foundation

- [ ] Varejo

- [ ] E-Commerce

- [ ] Supply Chain

- [ ] Geral

- [ ] TMS

- [ ] BackOffice

- [ ] Compras

- [ ] Quality

- [ ] healthcare

**Comment by dreissonmr** [comment]
Bom Dia Flavio,

Para que possamos analisar e dar o melhor direcionamento na sua solicitação, por favor nos forneça mais detalhes referente a criação desta API, como por exemplo: Nome da API, Descrição da API, Agrupador de Negócio e seu e-mail. 

Ficamos no aguardo.

**Comment by dreissonmr** [comment]
Não obtivemos nenhum retorno por parte do solicitante, quanto as informações que foram solicitadas ao mesmo.
